name: Build and Push Docker Image to Artifact Registry

on:
  push:
    branches:
      - main
      - add-workflow-to-build-and-publish-docker-image

env:
  PROJECT_ID: 'udemy-microsrv'
  AR_REGION: 'us-central1'
  AR_REPOSITORY: 'docker-images'
  IMAGE_NAME: 'udemy-microsrv-product'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Google Cloud Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.AR_REGION }}-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t ${{ env.AR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Push Docker Image to Artifact Registry
        run: docker push ${{ env.AR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
